version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(levelname)s: %(message)s  |> %(name)s: %(lineno)d'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout


loggers:
    development:
        level: DEBUG
        handlers: [console]
        propagate: no


root:
    level: INFO
    handlers: [console]